version: '2'

services:
  docker-angular:
    image: lparet/docker-ubuntu-angular:1.0
    container_name: docker-angular
    restart: always
    volumes:
      - /path/to/your/project:/var/www/html:rw